brand:
  name: [Открывая искусство]
menu-string: []

nav: # Navbar links
  - title: [Цель]
    url: '#targets'
  - title: [Авторы]
    url: '#team'
  - title: [Портфолио]
    url: '#portfolio'

copyright: ["© 2018 Dmitry. All rights reserved. " ]
copyright_url: ["https://t.me/medaved"]
copyright_text: [Telegram ME.]

social-buttons: # Footer social buttons


quicklinks: # Footer links


modal: # Modal strings for l10n