brand:
  name: [Открывая искусство]
menu-string: [Collapsed menu text]

nav: # Navbar links
  - title: [Проблема]
    url: '#problem'
  - title: [Цель]
    url: '#targets'
  - title: [Задачи]
    url: '#tasks'
  - title: [Формат мероприятия]
    url: '#event-format'
  - title: [План мероприятия]
    url: '#event-plan'
  - title: [Авторы]
    url: '#team'
  - title: [Портфолио]
    url: '#portfolio'

copyright: [Copyright notice]

social-buttons: # Footer social buttons
  - icon: [Font awesome icon code]
    url: '[Link]'
  - icon: [Font awesome icon code]
    url: '[Link]'

quicklinks: # Footer links
  - title: [Link title]
    url: '[Link]'
  - title: [Link title]
    url: '[Link]'

modal: # Modal strings for l10n